window.onload = function(){
	var audio = document.getElementById('mu4');
		audio.pause();
}
function play(){
	var audio = document.getElementById('mu4');
	if(audio.paused){
		audio.play();
		document.getElementById()
	}else{
		audio.pause();
		audio.currentTime = 0;
	}
}
$(function(){
	$("#p1").click(function(){
		$("#m1").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p2").click(function(){
		$("#m2").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p3").click(function(){
		$("#m3").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p4").click(function(){
		$("#m4").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p5").click(function(){
		$("#m5").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p6").click(function(){
		$("#m6").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p7").click(function(){
		$("#m7").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p8").click(function(){
		$("#m8").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p9").click(function(){
		$("#m9").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#p10").click(function(){
		$("#m10").fadeIn(500);
		$("#hahaha").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m1").fadeOut(0);
		$("#close").css("right","50px");
	});
	$("#close").click(function(){
		$("#hahaha").fadeIn(500);
		$("#m1").fadeOut(0);
		$("#m2").fadeOut(0);
		$("#m3").fadeOut(0);
		$("#m4").fadeOut(0);
		$("#m5").fadeOut(0);
		$("#m6").fadeOut(0);
		$("#m7").fadeOut(0);
		$("#m8").fadeOut(0);
		$("#m9").fadeOut(0);
		$("#m10").fadeOut(0);
		$("#close").css("right","-75px");
	});
});